 specify language
language: java

# specify language options
jdk:
- 1.8

# # configure which branches to run
# branches:
#   # whitelist
#   only:
#     - GitTravisCI
#     - master
#     - /^deploy-.*$/ # regex ok
#   # blacklist
#   except:
#     - TravisIntegration 
#     - TestRepo 
    
# after_script: # here's a build step block
# - echo "Say Hello"

# after_script:
# - test $TRAVIS_PULL_REQUEST = false \
#   && echo "not a pull request" \
#   && git push \
  
# notifications: # set notification options
#   email:
#     recipients:
#       - robert.murdoc@gmx.com

#     # change is when the repo status goes from pass to fail or vice versa
#     on_success: change
#     on_failure: always
    
#   # Or we could just disable all email
#   # email: false
    
# ## begin build steps
# ####################

# install: ./install-dependencies.sh
